on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
env:
  ATLANTIS_VERSION: v0.27.2
  TERRAGRUNT_VERSION: v0.57.5
  SOPS_VERSION: v3.8.1
  IMAGE: ghcr.io/${{github.repository}}
jobs:
  build_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            ATLANTIS_VERSION=${{ env.ATLANTIS_VERSION }}
            TERRAGRUNT_VERSION=${{ env.TERRAGRUNT_VERSION }}
            SOPS_VERSION=${{ env.SOPS_VERSION }}
          push: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
