on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
env:
  ATLANTIS_VERSION: v0.27.2
  TERRAGRUNT_VERSION: v0.57.5
  SOPS_VERSION: v3.8.1
  IMAGE: ghcr.io/${{github.repository}}
jobs:
  check_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -   id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.IMAGE }}
            tags: |
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}.{{patch}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}